// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package meme

import (
	"time"

	"github.com/adammy/memepen-services/pkg/template"
)

// CreateMeme defines a structure for creating a Meme.
type CreateMeme struct {
	// ImageID is the unique identifier of the base image used for the Meme.
	ImageID string `json:"imageId"`

	// Text is the text used in the Meme.
	Text []string `json:"text"`

	// TextStyles is the text field styling for this Meme.
	TextStyles []template.TextStyle `json:"textStyles"`
}

// Meme defines a structure for a meme.
type Meme struct {
	// CreatedOn defines the date/time the Meme was created.
	CreatedOn time.Time `json:"createdOn"`

	// ID is a unique identifier for the Meme.
	ID string `json:"id"`

	// ImageID is the unique identifier of the base image used for the Meme.
	ImageID string `json:"imageId"`

	// Text is the text used in the Meme.
	Text []string `json:"text"`

	// URL is the full URL to the Meme image.
	URL string `json:"url"`
}

// CreateMemeJSONBody defines parameters for CreateMeme.
type CreateMemeJSONBody = CreateMeme

// CreateMemeJSONRequestBody defines body for CreateMeme for application/json ContentType.
type CreateMemeJSONRequestBody = CreateMemeJSONBody
