// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package img

import (
	"time"
)

// CreateImageForm defines a base image to upload.
type CreateImageForm struct {
	// Image is the image to upload.
	Image string `json:"image"`
}

// CreateImageJSON defines where to upload a base image from.
type CreateImageJSON struct {
	// URL is the full URL to the base image.
	URL string `json:"url"`
}

// Image defines metadata for a base image.
type Image struct {
	// CreatedOn defines the date/time the base image was created.
	CreatedOn time.Time `json:"createdOn"`

	// Height is the height of the base image. We want this precalculated and stored to avoid continually calculating this.
	Height int `json:"height"`

	// ID is a unique identifier for the template.
	ID string `json:"id"`

	// URL is the full URL to the base image.
	URL string `json:"url"`

	// Width is the width of the base image. We want this precalculated and stored to avoid continually calculating this.
	Width int `json:"width"`
}

// CreateImageJSONBody defines parameters for CreateImage.
type CreateImageJSONBody = CreateImageJSON

// CreateImageJSONRequestBody defines body for CreateImage for application/json ContentType.
type CreateImageJSONRequestBody = CreateImageJSONBody
