// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package template

import (
	"time"
)

// Defines values for TextStyleFontFamily.
const (
	Arial     TextStyleFontFamily = "Arial"
	ComicSans TextStyleFontFamily = "Comic Sans"
	Impact    TextStyleFontFamily = "Impact"
)

// CreateTemplate defines a structure for creating a Template.
type CreateTemplate struct {
	// DefaultText is the text used to display Meme usage.
	DefaultText []string `json:"defaultText"`

	// ID is the unique identifier of the base image used for the Template.
	ImageID string `json:"imageId"`

	// Name is a user-friendly name for the Template.
	Name string `json:"name"`

	// TextStyles is the text field styling for this Template.
	TextStyles []TextStyle `json:"textStyles"`
}

// Template defines a structure for creating a Meme.
type Template struct {
	// CreatedOn defines the date/time the Template was created.
	CreatedOn time.Time `json:"createdOn"`

	// DefaultText is the text used to display Meme usage.
	DefaultText []string `json:"defaultText"`

	// ID is a unique identifier for the Template.
	ID string `json:"id"`

	// ImageID is the unique identifier of the base image used for the Template.
	ImageID string `json:"imageId"`

	// Name is a user-friendly name for the Template.
	Name string `json:"name"`

	// TextStyles is the text field styling for this Template.
	TextStyles []TextStyle `json:"textStyles"`
}

// TextStyle defines styling and positioning for text.
type TextStyle struct {
	// FontColor defines the color of the text in hexadecimal (e.g., "#FFFFFF").
	FontColor string `json:"fontColor"`

	// FontFamily defines the font family (e.g., "Helvetica").
	FontFamily TextStyleFontFamily `json:"fontFamily"`

	// FontSize defines the font size in point values.
	FontSize int `json:"fontSize"`

	// Rotation defines the number of degrees to rotate the text.
	Rotation *int `json:"rotation,omitempty"`

	// StrokeColor defines the color of the text stroke in hexadecimal (e.g., "#FFFFFF").
	StrokeColor *string `json:"strokeColor,omitempty"`

	// StrokeSize defines the size of the text stroke.
	StrokeSize *int `json:"strokeSize,omitempty"`

	// Width is the width of the text field.
	Width int `json:"width"`

	// X is the x-axis value representing the top-left of a text field.
	X int `json:"x"`

	// Y is the y-axis value representing the top-left of a text field.
	Y int `json:"y"`
}

// FontFamily defines the font family (e.g., "Helvetica").
type TextStyleFontFamily string

// CreateTemplateJSONBody defines parameters for CreateTemplate.
type CreateTemplateJSONBody = CreateTemplate

// UpdateTemplateJSONBody defines parameters for UpdateTemplate.
type UpdateTemplateJSONBody = CreateTemplate

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = CreateTemplateJSONBody

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody = UpdateTemplateJSONBody
